version: "3.9"

services:
  redis:
    image: redis:latest
    command: redis-server
    ports:
      - "6379:6379"
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 OnlineCinema.asgi:application
    ports:
      - "8000:8000"
    depends_on:
      - redis
